spring.datasource.url=jdbc:sqlserver://LAPTOP-05A05D:1433;databaseName=Afri_food_databank;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password= michael@247
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Default admin (created on startup if missing)
app.admin.email=admin@afrifood.com
app.admin.password=Admin@12345
app.admin.name=AfriFood Admin
